# Author: Cavelle Benjamin

variables:
  DOMAIN: "thecb4.io"
  EMAIL: "cavelle@thecb4.io"

stages:
  - build-test
  - docs

build_and_test:
  image:
    name: thecb4/swift-plus:latest
    entrypoint: [""]
  stage: build-test
  script:
    - swift package update
    - ./calm.swift continuous-integration
  only:
    - master

pages:
  image:
    name: thecb4/swift-plus:latest
  stage: docs
  dependencies:
    - build_and_test
  script:
    - ./calm.swift documentation
    - mkdir public
    - cp docs/index.html public/index.html
  artifacts:
    paths:
    - public
  only:
    - master
