#if !canImport(ObjectiveC)
  import XCTest

  extension PillowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PillowTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(PillowTests.__allTests__PillowTests)
    ]
  }
#endif
