#if !canImport(ObjectiveC)
  import XCTest

  extension PillowKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PillowKitTests = [
      ("testCodableTestCaseResultFailuresDecode", testCodableTestCaseResultFailuresDecode),
      ("testCodableTestCaseResultNoFailuresDecode", testCodableTestCaseResultNoFailuresDecode),
      ("testCodableTestCaseResultNoFailuresEncode", testCodableTestCaseResultNoFailuresEncode)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(PillowKitTests.__allTests__PillowKitTests)
    ]
  }
#endif
