#if !canImport(ObjectiveC)
  import XCTest

  extension CLITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CLITests = [
      ("testCLIParse", testCLIParse)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(CLITests.__allTests__CLITests)
    ]
  }
#endif
